# Generated by Django 4.2 on 2025-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Копирайтер', 'Копирайтер'), ('Администратор', 'Администратор'), ('Редактор', 'Редактор')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Утверждена', 'Утверждена'), ('Отклонена', 'Отклонена')], default='under_consideration', max_length=30, verbose_name='Статус новости'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика')], max_length=40, verbose_name='Тип новости'),
        ),
    ]
