# Generated by Django 4.2 on 2025-04-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdBanner',
            new_name='Banner',
        ),
    ]
