# Generated by Django 4.2 on 2025-04-30 09:51

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbanner',
            name='image',
            field=models.ImageField(help_text='Требования: горизонтальная ориентация, соотношение 1.91:1, минимум 600x314px, размер файла до 5МБ.', upload_to='ad_banner', validators=[api.validators.validate_ad_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Каптинка новости'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('copywriter', 'Копирайтер'), ('admin', 'Администратор'), ('redactor', 'Редактор')], default='user', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='news_images', validators=[api.validators.validate_image_aspect_ratio, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Каптинка новости'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('under_consideration', 'На рассмотрении'), ('approver', 'Утверждена'), ('rejected', 'Отклонена')], default='under_consideration', max_length=30, verbose_name='Статус новости'),
        ),
    ]
