# Generated by Django 4.2 on 2025-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('На рассмотрении', 'На рассмотрении'), ('Утверждена', 'Утверждена'), ('Отклонена', 'Отклонена')], default='На рассмотрении', max_length=30, verbose_name='Статус новости'),
        ),
    ]
