# Generated by Django 4.2 on 2025-05-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Спорт', 'Спорт'), ('Политика', 'Политика'), ('Культура', 'Культура'), ('Интернет', 'Интернет'), ('Наука и технологии', 'Наука и технологии'), ('Общество', 'Общество'), ('Преступность и право', 'Преступность и право'), ('Рейтинги', 'Рейтинги'), ('Религия', 'Религия'), ('Дни рождения', 'Дни рождения'), ('Экономика', 'Экономика')], max_length=40, verbose_name='Тип новости'),
        ),
    ]
