# Generated by Django 4.2 on 2025-05-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Копирайтер', 'Копирайтер'), ('Администратор', 'Администратор'), ('Редактор', 'Редактор')], default='Пользователь', max_length=20, verbose_name='Роль'),
        ),
    ]
